spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://<HOST>:<PORT>/<DATABASE>
    username: <USERNAME>
    password: <PASSWORD>
  data:
    redis:
      host: <HOST>
      port: <PORT>
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <CLIENTID>
            client-secret: <SECRET>
            redirect-uri: <URI>
            scope:
              - profile
              - email
google:
  userinfo:
    request:
      url: https://www.googleapis.com/oauth2/v2/userinfo
  token:
    request:
      url: https://oauth2.googleapis.com/token

jwt:
  secretKey: abcdefg
  accessTokenExpiration: <AT>
  refreshTokenExpiration: <RT>

logging:
  level:
    org.apache.http: INFO
    httpclient.wire: INFO

discord:
  url: <DISCORD_WEBHOOK>
