name: server CI with Gradle

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./backend"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: List files in the repository
        run: ls

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-executable: ./gradlew
